# command line: C:/Users/30138/Desktop/GHG-GCN/main.py

base_lr: 0.1
batch_size: 4
config: ./config/nturgbd120-cross-subject/default.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 120
  num_person: 1
  num_point: 50
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
test_batch_size: 4
test_feeder_args:
  bone: false
  data_path: D:/whq/dataset/NTU dataset/NTU120_CSub.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: D:/whq/dataset/NTU dataset/NTU120_CSub.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/ntu120/xsub/ctrgcn_joint
